_wandb:
    value:
        cli_version: 0.21.0
        e:
            oafqm4xlwldnfybrmug9fzoahicrur7u:
                args:
                    - --data
                    - /home/agrilab/Documentos/Casanova/Arvores/Dataset/dados/madeira_tangencial
                    - --epochs
                    - "150"
                    - --model
                    - yolo11m-cls.pt
                    - --project
                    - yolo11m-cls
                    - --name
                    - madeira_tangencial
                    - --wandb-project
                    - wood_classification
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "978790502400"
                        used: "666645774336"
                email: snaxofc10@gmail.com
                executable: /home/agrilab/miniconda3/bin/python
                gpu: NVIDIA GeForce RTX 4080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 9728
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080
                      uuid: GPU-11d750fe-0307-ecec-1a0a-2e10a459e8fb
                host: agrilab-4080
                memory:
                    total: "66511335424"
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.35
                program: /home/agrilab/Documentos/Casanova/Arvores/Dataset/src/train.py
                python: CPython 3.13.2
                root: /home/agrilab/Documentos/Casanova/Arvores/Dataset/src
                startedAt: "2025-11-02T15:07:00.590001Z"
                writerId: oafqm4xlwldnfybrmug9fzoahicrur7u
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.13.2
            "5": 0.21.0
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
batch:
    value: -1
dataset:
    value: /home/agrilab/Documentos/Casanova/Arvores/Dataset/dados/madeira_tangencial
dropout:
    value: 0.1
epochs:
    value: 150
imgsz:
    value: 224
lr0:
    value: 0.01
mixup:
    value: 0.1
model_id:
    value: yolo11m-cls
optimizer:
    value: auto
patience:
    value: 50
resolved_weights:
    value: yolo11m-cls.pt
